1. #1.
Q1. Create a DataFrame with the following student marks and display students with marks above 80.
{'Name': ['Anu', 'Raj', 'Diya', 'Kiran'], 'Marks': [76, 88, 95, 65]}

expected Output:
    
    Name  Marks
1   Raj     88
2  Diya     95

In [5]:
import pandas as pd
data={'Name': ['Anu', 'Raj', 'Diya', 'Kiran'], 'Marks': [76, 88, 95, 65]}
df=pd.DataFrame(data)
student_mark=df[df['Marks']>80]
student_mark

   Name  Marks
1   Raj     88
2  Diya     95

#2.Q2. Create a DataFrame and find the mean salary grouped by department.
{'Name': ['Amit', 'Sneha', 'Kunal', 'Riya'], 'Department': ['HR', 'IT', 'HR', 'IT'], 'Salary': [30000, 50000, 35000, 52000]}
Expected Output:
Department
HR    32500.0
IT    51000.0
Name: Salary, dtype: float64

In [10]:
import pandas as pd
data={'Name': ['Amit', 'Sneha', 'Kunal', 'Riya'], 'Department': ['HR', 'IT', 'HR', 'IT'], 'Salary': [30000, 50000, 35000, 52000]}
df=pd.DataFrame(data)
dept=df.groupby('Department')['Salary'].mean()
dept

Department
HR    32500.0
IT    51000.0
Name: Salary, dtype: float64

#3.Q3. Create a DataFrame and apply label encoding to the Gender column.
{'Name': ['Arjun', 'Leela', 'Kiran'], 'Gender': ['Male', 'Female', 'Male']}
Expected Output:
    Name  Gender  Gender_encoded
0  Arjun    Male               1
1  Leela  Female               0
2  Kiran    Male               1

In [12]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
data={'Name': ['Arjun', 'Leela', 'Kiran'], 'Gender': ['Male', 'Female', 'Male']}
df=pd.DataFrame(data)
encoder=LabelEncoder()
df['Gender_encoded']=encoder.fit_transform(df['Gender'])
df

    Name  Gender  Gender_encoded
0  Arjun    Male               1
1  Leela  Female               0
2  Kiran    Male               1

#4.🔹Q4. Normalize the 'Score' column using Min-Max scaling.
{'Student': ['A', 'B', 'C'], 'Score': [55, 80, 65]}

Expected Output:
    Student  Score  Normalized_Score
0       A     55               0.0
1       B     80               1.0
2       C     65               0.4

In [20]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
data={'Student': ['A', 'B', 'C'], 'Score': [55, 80, 65]}
df=pd.DataFrame(data)
sc=MinMaxScaler()
df['Normalized_Score']=sc.fit_transform(df[['Score']])
df

  Student  Score  Normalized_Score
0       A     55               0.0
1       B     80               1.0
2       C     65               0.4

#5.
Use SVM, RandomForest, and GaussianNB to classify customers as 'Buy' or 'Not Buy' based on Age and Salary.
{'Age': [22, 25, 47, 52, 46, 56, 23], 'Salary': [15000, 29000, 48000, 60000, 52000, 61000, 17000], 'Buy': [0, 0, 1, 1, 1, 1, 0]}

In [23]:
import pandas as pd
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
data={'Age': [22, 25, 47, 52, 46, 56, 23], 'Salary': [15000, 29000, 48000, 60000, 52000, 61000, 17000], 'Buy': [0, 0, 1, 1, 1, 1, 0]}
df=pd.DataFrame(data)
df

   Age  Salary  Buy
0   22   15000    0
1   25   29000    0
2   47   48000    1
3   52   60000    1
4   46   52000    1
5   56   61000    1
6   23   17000    0

In [25]:
x=df[['Age','Salary']]
y=df['Buy']
from sklearn.model_selection import train_test_split
(x_train,x_test,y_train,y_test)=train_test_split(x,y,test_size=0.30,random_state=42)

In [26]:
svc=SVC()
svc.fit(x_train,y_train)
svc_pred=svc.predict(x_test)
rf=RandomForestClassifier()
rf.fit(x_train,y_train)
rf_pred=rf.predict(x_test)
gb=GaussianNB()
gb.fit(x_train,y_train)
gb_pred=gb.predict(x_test)

In [32]:
from sklearn.metrics import accuracy_score
svc_accuracy=accuracy_score(y_test,svc_pred)
print("The SVC accuracy score is:",svc_accuracy)
print("The RandomForest score is:",accuracy_score(y_test,rf_pred))
print("The GaussianNB score is:",accuracy_score(y_test,rf_pred))

The SVC accuracy score is: 0.6666666666666666
The RandomForest score is: 1.0
The GaussianNB score is: 1.0