In [ ]:
#1.
from sklearn.preprocessing import LabelEncoder
df['gender'] = LabelEncoder().fit_transform(df.gender)
df = pd.get_dummies(df, columns=['gender'])

In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
data={'Age':[23,25,32,12],'gender':['male','female','male','female']}
df=pd.DataFrame(data)
encoder=LabelEncoder()
df['gender']=encoder.fit_transform(df['gender'])
df

   Age  gender
0   23       1
1   25       0
2   32       1
3   12       0

In [ ]:
#2.
from sklearn.tree import DecisionTreeClassifier

y = ['yes', 'no', 'yes', 'no']
model = DecisionTreeClassifier()
model.fit(X, y)

In [2]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
x=[['1'],['2'],['3'],['4']]
y = ['yes', 'no', 'yes', 'no']
encode=LabelEncoder()
y=encode.fit_transform(y)
model = DecisionTreeClassifier()
model.fit(x, y)
predict=model.predict([[3]])
predict

array([1])

In [13]:
#3.
X = data.drop(data['Purchased'], axis=1)
y = data['Purchased']
X = X.drop(data['Purchased'], axis=1)  

#I am not aware in this code

AttributeError: 'list' object has no attribute 'drop'

In [ ]:
#4.
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier(max_depth=None)  
model.fit(X, y)

model.score(X, y)

In [4]:
from sklearn.tree import DecisionTreeClassifier

x=[[1,2],[2,3],[3,4]]
y=['red','green','yellow']

model = DecisionTreeClassifier(max_depth=2)  
model.fit(x, y)

model.score(x, y)

1.0

In [ ]:
#5.
from sklearn.preprocessing import MinMaxScaler
import numpy as np

data = [[-1, 2], [0, 0], [1, 2]]
scaler = MinMaxScaler()
scaler.fit(data)
print(scaler.transform())

In [5]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

data = [[-1, 2], [0, 0], [1, 2]]
scaler = MinMaxScaler()
scaler.fit(data)
print(scaler.transform(data))

[[0.  1. ]
 [0.5 0. ]
 [1.  1. ]]

In [ ]:
#6.
from sklearn.metrics import accuracy_score

y_true = [1, 0, 1]
y_pred = [1, 1, 0]

acc = accuracy_score()
print("Accuracy:", acc)

In [6]:
from sklearn.metrics import accuracy_score

y_true = [1, 0, 1]
y_pred = [1, 1, 0]

acc = accuracy_score(y_true,y_pred)
print("Accuracy:", acc)

Accuracy: 0.3333333333333333

In [ ]:
#7.
from sklearn.model_selection import train_test_split
import numpy as np

X = np.array([[1, 2], [3, 4], [5, 6]])
y = np.array([0, 1])

X_train, X_test, y_train, y_test = train_test_split(X, y)

In [7]:
from sklearn.model_selection import train_test_split
import numpy as np

X = np.array([[1, 2], [3, 4], [5, 6]])
y = np.array([0, 1,0])

X_train, X_test, y_train, y_test = train_test_split(X, y)

In [ ]:
#8.
import pandas as pd

df = pd.DataFrame({
    'Feature': ['1', '2', 'three']
})

df['Feature'] = df['Feature'].astype(int)

In [8]:
import pandas as pd

df = pd.DataFrame({'Feature': ['1', '2', 'three']})

df['Feature'] =pd.to_numeric(df['Feature'],errors='coerce').fillna(3).astype('int64')
df

   Feature
0        1
1        2
2        3

In [ ]:
#9
from sklearn.tree import DecisionTreeClassifier

X = [[1, 2], [3, 4], [5, 6]]
y = ['yes', 'no'] 
clf = DecisionTreeClassifier()
clf.fit(X, y)

In [9]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
X = [[1, 2], [3, 4], [5, 6]]
y = ['yes', 'no','yes'] 
encode=LabelEncoder()
y=encode.fit_transform(y)
clf = DecisionTreeClassifier()
clf.fit(X, y)
print(clf.predict([[5,6]]))

[1]

In [ ]:
#10.
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression

iris = load_iris()
X, y = iris.data, iris.target

model = LogisticRegression()
model.fit(X, y)
print(model.predict_proba([[5.1, 3.5]]))

In [10]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression

iris = load_iris()
X, y = iris.data, iris.target

model = LogisticRegression()
model.fit(X, y)
print(model.predict_proba([[5.1,2.5,4.2, 3.5]]))

[[1.92430966e-04 1.33849593e-02 9.86422610e-01]]

C:\Anaconda3\envs\ai\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(